/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentationSidebar: [
    {type:"autogenerated", dirName:"docs"}
  ],
  apiSidebar: [
    {type:"autogenerated", dirName:"api"}
  ],
  pluginSidebar: [
    {type:"autogenerated", dirName:"plugin"}
  ],
};

module.exports = sidebars;
