label: ⚙️ Config Files
position: 4
link:
  type: generated-index
  title: Config Files
  slug: category/api-config
  description: Here you can find all available variables in the config files from Open Ticket v4.