label: ⚙️ Config Files
position: 3
link:
  type: generated-index
  title: Config Files
  slug: category/api-config
  description: Here you can find all variables available in the config files from Open Ticket v4.